from datetime import date, datetime
from typing import Protocol

from ..models import DeliveryReceipt, Digest, Story, UsageSummary


class StateStore(Protocol):
    def initialize(self) -> None: ...
    def story_exists(self, canonical_url: str) -> bool: ...
    def upsert_story(self, story: Story) -> str: ...
    def get_recent_stories(self, since: datetime) -> list[Story]: ...
    def record_run_start(self, local_date: date, forced: bool) -> str: ...
    def record_run_finish(self, run_id: str, status: str, error: str | None = None) -> None: ...
    def get_successful_runs(self, local_date: date) -> int: ...
    def get_usage(self, local_date: date) -> UsageSummary: ...
    def reserve_budget(self, run_id: str, local_date: date, provider: str, model: str,
                       reserved_cost_usd: float, monthly_limit_usd: float) -> str | None: ...
    def list_budget_reservations(self, local_month: str, state: str | None = None,
                                 limit: int = 100) -> list[dict[str, object]]: ...
    def release_budget_reservation(self, reservation_id: str, reason: str) -> bool: ...
    def list_stale_records(self, before: datetime) -> dict[str, list[dict[str, object]]]: ...
    def record_usage_and_reconcile(self, reservation_id: str, run_id: str, local_date: date,
                                   provider: str, model: str, input_tokens: int, output_tokens: int,
                                   estimated_cost_usd: float) -> None: ...
    def record_usage(self, run_id: str, local_date: date, provider: str, model: str, input_tokens: int,
                     output_tokens: int, estimated_cost_usd: float | None) -> None: ...
    def record_digest(self, digest: Digest, run_id: str) -> str: ...
    def get_digest(self, digest_id: str) -> Digest | None: ...
    def get_digest_story_ids(self, digest_id: str) -> list[str]: ...
    def reserve_delivery(self, digest_date: date, run_id: str, force: bool = False) -> str | None: ...
    def update_delivery(self, delivery_id: str, state: str, digest_id: str | None = None,
                        error: str | None = None) -> None: ...
    def get_delivery(self, delivery_id: str) -> dict[str, object] | None: ...
    def list_deliveries(self, limit: int = 20) -> list[dict[str, object]]: ...
    def complete_delivery(self, delivery_id: str, digest_id: str, sent_at: datetime,
                          receipt: DeliveryReceipt) -> None: ...
    def mark_digest_sent(self, digest_id: str, sent_at: datetime) -> None: ...
    def digest_sent_for_date(self, digest_date: date) -> bool: ...
    def get_last_run(self) -> dict[str, object] | None: ...
