from datetime import date, datetime
from typing import Protocol

from ..models import Digest, Story, UsageSummary


class StateStore(Protocol):
    def initialize(self) -> None: ...
    def story_exists(self, canonical_url: str) -> bool: ...
    def upsert_story(self, story: Story) -> str: ...
    def get_recent_stories(self, since: datetime) -> list[Story]: ...
    def record_run_start(self, local_date: date, forced: bool) -> str: ...
    def record_run_finish(self, run_id: str, status: str, error: str | None = None) -> None: ...
    def get_successful_runs(self, local_date: date) -> int: ...
    def get_usage(self, local_date: date) -> UsageSummary: ...
    def record_usage(self, run_id: str, local_date: date, provider: str, model: str, input_tokens: int,
                     output_tokens: int, estimated_cost_usd: float | None) -> None: ...
    def record_digest(self, digest: Digest, run_id: str) -> str: ...
    def mark_digest_sent(self, digest_id: str, sent_at: datetime) -> None: ...
    def digest_sent_for_date(self, digest_date: date) -> bool: ...
    def get_last_run(self) -> dict[str, object] | None: ...
